server:
  servlet:
    context-path: /Kite
    session:
      cookie:
        http-only: true
  port: 9002
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://132.232.45.176:3306/kite?serverTimezone=UTC&useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: root
    password: qq735519898

    druid:
#      platform: mysql
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT1FROMDUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall,log4j2
#      logSlowSql: true

  devtools:
    restart:
      enabled: false
#    jms:
#      pub-sub-domain: true
#    activemq:
#      broker-url: failover:(tcp://192.168.1.54:61618)?timeout=2000
logging:
  config: classpath:log4j2-dev.xml